x/app/home/__init__.py
# app/admin/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

x/app/home/views.py
from flask import abort, render_template, request, jsonify
from flask_login import current_user, login_required

from . import home
from app.models import *


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")


@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)

    return render_template('home/admin_dashboard.html', title="Dashboard")


# @user.route('/interactive/', methods=['GET', 'POST'])
# def interactive():
#
#     return render_template("user/interactive.html")
#
# @user.route('/background_process')
# def background_process():
#     # cols = getColumns(User)
#     # UsersList = User.query.all()
#
#     try:
#         lang = request.args.get('proglang', 0, type=str)
#         if lang.lower() == 'python':
#
#             return jsonify(result='You are wise')
#         else:
#             return jsonify(result='Try again.')
#     except Exception as e:
#         return str(e)

@home.route('/tables')
def viewtables():
    return render_template("home/view_tables.html")


@home.route('/gettables', methods=['GET'])
def gettables():
    table = str(request.args.get('mytable')).lower()

    if table == 'user':
        ideas = User.query.order_by('username')
        return getTable(ideas)
    if table == 'career':
        ideas = Career.query.all()
        return getTable(ideas)
    if table == 'role':
        ideas = Role.query.all()
        return getTable(ideas)
    if table == 'note':
        ideas = Note.query.all()
        return getTable(ideas)
    else:
        error = {
            'status': '404',
            'msg': 'unable to retrieve ideas'
        }
        return jsonify(error)


def getColumns(modelclass):
    from sqlalchemy import inspect
    mapper = inspect(modelclass)
    return [c.key for c in mapper.attrs]


def getTable(ideas):
    # ideas = User.query.order_by('username')
    # d = [i.serialize() for i in ideas]

    if ideas:
        m = []
        querylist = []
        for i in ideas:
            try:
                q = i.serialize()
                querylist.append(q)
            except:
                m.append('error')

        data = {
            'status': 'OK',
            'ideas': querylist,
            'msg': m
        }
        return jsonify(data)
    else:
        error = {
            'status': 404,
            'ideas': None,
            'msg': 'unable to retrieve ideas'
        }
        return jsonify(error)

x/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | Note Taking 101 </title>

    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/jquery.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/colReorder.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/buttons.dataTables.min.css') }}" rel="stylesheet">
    
    <script src="{{ url_for('static', filename='lib/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/jquery-1.12.4.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/dataTables.colReorder.min.js') }}"></script>
    
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Home</a>
              <a class="navbar-brand topnav" href="mailto:sshc625@gmail.com?Subject=Hello%20from%20GeneSearchAPI" target="_top">Contact Me</a>
              <a class="navbar-brand topnav" href="http://github.com/shsun" target="_blank">Go to my Git</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        {% if current_user.is_admin %}
                            <li><a href="{{ url_for('home.admin_dashboard') }}">Dashboard</a></li>
                            <li><a href="{{ url_for('user.viewprofile') }}">View Profile</a></li>
                            <li><a href="{{ url_for('admin.list_careers') }}">Careers</a></li>
                            <li><a href="{{ url_for('admin.list_roles') }}">Roles</a></li>
                            <li><a href="{{ url_for('admin.list_users') }}">Users</a></li>
                          {% else %}
                            <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                            <li><a href="{{ url_for('user.viewprofile') }}">View Profile</a></li>
                            <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.username }}!</a></li>
                        {% endif %}
                    {% else %}
                      <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                      <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                      <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% endif %}
                </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        {% if current_user.is_authenticated %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        {% else %}
                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                          <li class="footer-menu-divider">⋅</li>
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                    <p class="copyright text-muted small">Novero Sample Flask App</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

x/app/templates/home.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>home</title>
  </head>
  <body>
    <h1>welcome {{username}} , this is home</h1>
  </body>
</html>

x/app/templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>login</title>
  </head>
  <body>
    <form  style="margin:20px;border:1px solid red" method="post" action="/login">
        <span>username:</span><input type="text" name="username" id="username"><br/>
        <span>password:</span><input type="password" name="password" id="password"><br/>
        <button type="submit" id="loginBtn">sign-in</button>
    </form>
    {% if error %}
        <h1 style="color:red">{{ error }}!</h1>
    {% endif %}
  </body>
</html>